version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: mdillon/postgis
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
    volumes:
      - /data/pgdata:/var/lib/postgresql/data

  sentry:
    build: .
    container_name: sentry-localdev
    environment:
      - SENTRY_SECRET_KEY=abc
      - SENTRY_REDIS_HOST=redis
      - SENTRY_DB_NAME=sentry
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_USER=sax
      - SENTRY_PASSWORD=123
      - C_FORCE_ROOT=1 # never in production
    links:
      - "redis:redis"
      - "postgres:postgres"
    ports:
      - 9000:9000
    volumes:
      - /data/sentry:/conf
